/** Who may see a roll. Enforced by RLS in `dice`, mirrored here for the UI. */
export type RollVisibility = 'table' | 'dm' | 'secret';

/** A physical die group: `count` dice of `sides` faces. `tag` lets systems tell groups apart (own vs shared pool vs opposition). */
export interface DiceGroup {
  count: number;
  sides: number;
  tag?: string;
}

/**
 * The intention of a roll, produced by a system's `engine.poolFor` (or by the
 * free roller). The server generates the dice; the client never does.
 */
export interface RollRequest {
  systemId: string | null;           // null → free roll
  kind: 'system' | 'free';
  title: string;                     // e.g. "Combate · Armas improvisadas"
  groups: DiceGroup[];
  /** Opaque, system-specific options (specialty, armour penalty, extra dice, target…). Validated by the system. */
  options?: Record<string, unknown>;
  /** Shared-resource dice taken for this roll, e.g. { destiny: 2 }. Debited atomically with the roll. */
  sharedResources?: Record<string, number>;
  visibility: RollVisibility;
  characterId?: string | null;
  modifier?: number;
}

/** Raw dice as generated by the server, grouped in the same order as the request. */
export type RolledDice = number[][];

/** What a system's `engine.resolve` returns. `summary` is what chat/registry show; `effects` are patches to apply. */
export interface RollResult {
  summary: string;
  detail?: Record<string, unknown>;
  /** e.g. { destinyUp: true, fortuneRefill: true } → the platform applies them through the system's engine. */
  effects?: Record<string, unknown>;
  total?: number;
}
